name: Publish package on NPM
on:
  release:
    types: [prereleased]
# Permission forced by repo-level setting; only elevate on job-level
permissions:
  contents: read
  # packages: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: |
          yarn
          make build && yarn publish --access=public --tag=beta
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
